/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TopFormSection from '@/components/topFormSection/TopFormSection'
import Featured from '@/components/featured/Featured'
import { useRouter } from 'next/router'
import { PageTracker } from '../../utils/PageTracker'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ content }) {

  const router = useRouter()

  PageTracker(router.asPath)
  return (
    <div className={styles.container}>
      <Head>
        <title>World's most advance practical legal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopFormSection content={content} />
      <Featured />

    </div>
  )
}

// Here i used getServerSideProps for api calling to make app more faster
export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/topFormSectionContent")
  const data = await res.json()
  return {
    props: {
      content: data[0].htmlContent,
    },
  };
}

